[jobs.run]
command = ["just", "run"]
need_stdout = true

[jobs.test]
command = ["just", "unit-test"]
need_stdout = true

[jobs.test-all]
command = ["just", "test"]
need_stdout = true

[jobs.nextest]
command = ["just", "unit-nextest"]
need_stdout = true

[jobs.nextest-all]
command = ["just", "nextest"]
need_stdout = true

[keybindings]
shift-t = "job:test-all"
shift-n = "job:nextest-all"
