ignore_merge_commits = true
tag_prefix = "v"
pre_bump_hooks = [
  "cargo set-version {{version}}",
]

[git_hooks.commit-msg]
path = "hooks/commit-msg.sh"

[git_hooks.pre-push]
path = "hooks/pre-push.sh"
